/* This file was generated by qmake with the info from <root>/src/corelib/corelib.pro. */
#ifndef QT_QTCORE_VERSION_H
#define QT_QTCORE_VERSION_H
#define QTCORE_VERSION_STR "5.1.0"
#define QTCORE_VERSION 0x050100
#endif // QT_QTCORE_VERSION_H
