/* This file was generated by qmake with the info from <root>/src/widgets/widgets.pro. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H
#define QTWIDGETS_VERSION_STR "5.1.0"
#define QTWIDGETS_VERSION 0x050100
#endif // QT_QTWIDGETS_VERSION_H
